### ISSUE TITLE
tensorflow and keras version

### ISSUE THREAD

**Issue by cassioalmeidas** [achillesheel02/ksl-mediapipe#1]
which tensorflow and keras version used?
I'm not able to run, the error:

`
ValueError: Please initialize `TimeDistributed` layer with a `Layer` instance. You passed: <keras.layers.convolutional.Conv1D object at 0x7fe500db7950>

`

**Comment by achillesheel02** [comment]
I was using Tensofrlow 2.3.1 and Keras 2.4..3
I've updated the repo with clearer instructions on how to go about using it.
